pipeline {
    agent any

    stages {
        stage('Clone Terraform repo') {
            steps {
                echo 'Cloning...'
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/shamimice03/jenkins-hands-on.git']])
        }}
        stage('Infra provisioning...') {
            steps {
                sh """
                    terraform init
                    terraform plan
                    terraform apply --auto-approve
                """
                sh 'pwd'
            }
        }
        stage('Procced to destroy the infra ?') {
            steps {
                input message: 'Destroy aws resources?'
            }
        }
        stage('Destroying...') {
            steps {
                sh 'terraform destroy --auto-approve'
            }
        }
    }
}
